### ISSUE TITLE
[Refactor] Enum을 활용해 Fixture 만들기

### ISSUE THREAD

**Issue by langoustinee** [four-uncles/saramara-community-server#103]
[이전 PR](https://github.com/four-uncles/saramara-community-server/pull/102)에서는 별도의 팩토리 클래스에서 픽스처를 제공할 메서드를 제공하는 방식을 사용했습니다.

그런데 이때, **Enum을 활용**하여 픽스처를 구성하는 방법으로 개선할 생각입니다. Enum을 통해 픽스처를 구성한다면 아래와 같은 이점을 얻을 수 있을 것으로 보입니다.

> - **타입 안정성**: Enum 자체가 하나의 타입이므로, 컴파일 타임에 타입 안정성을 제공합니다. 이는 잘못된 타입의 픽스처를 사용하는 실수를 방지할 수 있습니다.
> - **불변성**: Enum 인스턴스는 생성 후에 변경할 수 없으므로, 테스트 간에 픽스처가 변하는 것을 방지할 수 있습니다. 이는 테스트의 신뢰성을 높입니다.
> - **재사용성**: Enum 인스턴스는 전역적으로 접근 가능하므로, 필요한 곳에서 쉽게 재사용할 수 있습니다.
> - **명확한 의도 전달**: 각 Enum 값은 그 자체로 의미를 가질 수 있으므로, 코드를 읽는 사람에게 픽스처의 의도를 명확하게 전달할 수 있습니다.

물론 이는 정답이라기보다는 픽스처를 구성하는 다양한 방식 중 하나에 속합니다. 다만, 개인적으로 Enum을 이용해 픽스처를 꾸리는 방법이 시간적으로나 비용적으로 유의미하다고 생각되어 이를 공통 픽스처 설정하는데 활용하려고 합니다.

**Comment by IToriginal** [comment]
픽스처 구성에 여러가지 방법이 있는 것을 알게 되었네요. 이전 PR에서 좋은 고민을 해서 `Enum을 통한 Fixture 생성`까지 궁금해졌습니다. 👍🏻
저도 Fixture에 대해 좋은 생각이 떠오르면 팀원들에게 공유하겠습니다. 🤔
