### ISSUE TITLE
[Global/Fix] dto 패키지 분리

### ISSUE THREAD

**Issue by langoustinee** [four-uncles/saramara-community-server#129]
기존의 이너 클래스로 작성된 DTO를 Record로 전환하던 중 패키지 구조에 대한 부분이 아래와 같음을 확인했습니다.

```
ㄴboard
  ㄴ controller
    ㄴ dto
      ㄴ reqeust
  ㄴ service
    ㄴ dto
      ㄴ request
      ㄴ response
```

여기서 dto 패키지가 결국 여러 패키지 안에 중복으로 두게 되는데 이를 아래처럼 바꾸어 보다 편하게 접근할 수 있도록 수정하려 합니다.

```
ㄴboard
  ㄴ controller
  ㄴ service
  ㄴ dto
    ㄴ api
      ㄴ reqeust
    ㄴ business
      ㄴ reqeust
      ㄴ response
```

이렇게 하면 controller나 service 내부로 일일이 접근하지 않고 상위의 dto 패키지 내에서 presentation 계층에 사용되는 api DTO와 business 계층에서 사용되는 DTO를 구분하여 관리항 수 있다고 생각됩니다!

**Comment by langoustinee** [comment]
Board 패키지 먼저 DTO 분리하여 수정해두겠습니다.
댓글과 회원 쪽도 작업하시고 마지막 분이 이슈 닫아주시면 감사하겠습니다!

**Comment by IToriginal** [comment]
댓글 도메인 dto 패키지 분리 작업 마쳤습니다.✨

**Comment by langoustinee** [comment]
`member` 패키지의 변경 사항은 제가 작업하겠습니다.

**Comment by IToriginal** [comment]
투표 도메인에서도 dto 패키지 분리 작업으로 기능 개발을 진행하였습니다.✨
