### ISSUE TITLE
[Global/Feat] Controller 테스트 작성하기

### ISSUE THREAD

**Issue by IToriginal** [four-uncles/saramara-community-server#131]
`@Valid`에 대해 논의하면서 Dto 클래스의 검증이 정상적으로 작동하는지 확인했었습니다.
이에따라 Controller 테스트의 필요성을 알게되었고, 이를 진행하고자 합니다.

**Comment by langoustinee** [comment]
Board 패키지의 컨트롤러 테스트 작성읋 시작하겠습니다!
@WebMvcTest를 활용한 슬라이스 테스트 방식으로 진행할 예정입니다.

**Comment by IToriginal** [comment]
Comment 패키지 컨트롤러 테스트 작성 마쳤습니다.✨

**Comment by langoustinee** [comment]
@byeongJoo05 @IToriginal 회원 관련 진행사항은 저와 헌욱님이 투표 개발 완료와 더불어 병행하여 개발하는 방향으로 나아가도 좋을 것 같습니다.

**Comment by langoustinee** [comment]
해당 이슈는 제가 회원 도메인 컨트롤러 테스트 작성 이후 닫도록 하겠습니다!

**Comment by IToriginal** [comment]
투표 도메인에 슬라이스 테스트의 개발이 완료되어 이슈 연결토록 하겠습니다.
